### ISSUE TITLE
Multiple Problems

### ISSUE THREAD

**Issue by rouing** [Xon/XenForo2-ViewStickyThreads#1]
Permission does not show up and you cannot uninstall the VST addon. This mod is not even initialized.

**Comment by Xon** [comment]
Add-on support is only offered via https://xenforo.com/community/threads/view-sticky-threads.139138/ for valid XenForo customers

3rd party add-on compatibility is only provided via best effort.

**Comment by rouing** [comment]
When first installed it required that the _data folder was present. I got it fixed on my end. Just an FYI

**Comment by Gittified** [comment]
> When first installed it required that the _data folder was present. I got it fixed on my end. Just an FYI

What did you do for the fix?
