### ISSUE TITLE
Add-on does not at all work, warning displayed upon installation

### ISSUE THREAD

**Issue by zefirzdravkov** [Xon/XenForo2-ViewStickyThreads#3]
Hello!
Upon installation the following warning is displayed:
`To prevent potential issues, please resolve the following warnings before continuing:
The hashes.json file for this add-on is missing so no file health check can be performed.`

I proceeded with the installation of the add-on, however, no new permissions were to be seen on the "node permissions" page, neither was it automatically displaying sticky threads when "view other threads" was set to "no"

**Comment by Xon** [comment]
Support is only provided via https://xenforo.com/community/resources/view-sticky-threads.5962/

**Comment by zefirzdravkov** [comment]
I'm not requesting support, I'm reporting an issue and generally this is the function of the "issues" section on GitHub. I can provide you with more details if you ask me and I will manually install the addon without any support once this is resolved.

**Comment by Xon** [comment]
The various XenForo 2 repositories are not in a production installable state, you need to use a production redistributable for XenForo 2 add-on. Not jus clone the repository and try to use the web-installer.
