### ISSUE TITLE
Add-On Help

### ISSUE THREAD

**Issue by KezaTee** [Xon/XenForo2-ViewStickyThreads#4]
Hello,

I am trying to make the sticky threads appear when I have privated section for all registered users.
So they will only be able to see the sticky threads and their own posts. How do I activate this add-on? There is no setting to edit or to enable this to work and when I disable the "Permission to view other threads" it doesn't show up.

**Comment by Xon** [comment]
This add-on is quite simple.

Just revoke/deny the "View other threads" permission and grant the "View sticky threads" permission

**Comment by KezaTee** [comment]
Where is the "View sticky threads" it doesn't show anything for me?
